const { data } = that;

delete data.tags.label;
delete data.tags.placeLabel;
delete data.tags.homePlace;
delete data.tags.instURL;
delete data.tags.instSetting;
delete data.tags.lineTo;
delete data.tags.lineToValue;
delete data.tags[data.tags.dimension];
delete data.tags[data.tags.dimension + 'X'];
delete data.tags[data.tags.dimension + 'Y'];
delete data.tags[data.tags.dimension + 'Z'];
delete data.tags[data.tags.dimension + 'RotationX'];
delete data.tags[data.tags.dimension + 'RotationY'];
delete data.tags[data.tags.dimension + 'RotationZ'];
delete data.tags.dimension;
delete data.tags.color;
delete data.tags.scale;
delete data.tags.studioId;
delete data.tags.originType;
delete data.tags.instSetting;
delete data.tags.biosSetting;