const { data } = that;

delete data.tags.chosenEggName;
delete data.tags.eggSetupLabel;
delete data.tags.eggSetupLabelColor;
delete data.tags.eggSetupLabelFloatingBackgroundColor;
delete data.tags.color;
delete data.tags.chosenStudio;
delete data.tags.eggConfigConfirmed;
delete data.tags[data.tags.dimension];
delete data.tags[data.tags.dimension + 'X'];
delete data.tags[data.tags.dimension + 'Y'];
delete data.tags[data.tags.dimension + 'Z'];
delete data.tags[data.tags.dimension + 'RotationX'];
delete data.tags[data.tags.dimension + 'RotationY'];
delete data.tags[data.tags.dimension + 'RotationZ'];
delete data.tags.dimension;
delete data.tags.prevBotID;
delete data.tags.studioStationID;
delete data.tags.lineTo;