const { data } = that;

delete data.tags.label;
delete data.tags.labelColor;
delete data.tags.labelFloatingBackgroundColor;
delete data.tags.color;
delete data.tags[data.tags.dimension + "X"];
delete data.tags[data.tags.dimension + "Y"];
delete data.tags[data.tags.dimension + "Z"];
delete data.tags[data.tags.dimension + "RotationX"];
delete data.tags[data.tags.dimension + "RotationY"];
delete data.tags[data.tags.dimension + "RotationZ"];
delete data.tags[data.tags.dimension];
delete data.tags.dimension;
delete data.tags.simID;
delete data.tags.form;
delete data.tags.formSubtype;
delete data.tags.formAddress;
delete data.tags.formAddressAspectRatio;
delete data.tags.simAttributes;
delete data.tags.roleLocked;
delete data.tags.roleStack;
delete data.tags.roleName;
delete data.tags.roleOwner;
delete data.tags.simAttributesStartingValues;
delete data.tags.statsButton;
delete data.tags.defaultPlace;
delete data.tags.numUsers;