const { data } = that;

delete data.tags.label;
delete data.tags.labelColor;
delete data.tags.labelFloatingBackgroundColor;
delete data.tags.color;
delete data.tags[data.tags.dimension + "X"];
delete data.tags[data.tags.dimension + "Y"];
delete data.tags[data.tags.dimension + "Z"];
delete data.tags[data.tags.dimension + "RotationX"];
delete data.tags[data.tags.dimension + "RotationY"];
delete data.tags[data.tags.dimension + "RotationZ"];
delete data.tags[data.tags.dimension];
delete data.tags.dimension;
delete data.tags.placePrompt;
delete data.tags.formAddress;
delete data.tags.skybox;
delete data.tags.simID;
delete data.tags.skyboxGenerating;
delete data.tags.chosenDimension;
delete data.tags.doors;
delete data.tags.miniSkybox;
delete data.tags.lowRes;
delete data.tags.medRes;
delete data.tags.highRes;
delete data.tags.desktopGeneration;