const { data } = that;

delete data.tags.label;
delete data.tags.labelColor;
delete data.tags.labelFloatingBackgroundColor;
delete data.tags.color;
delete data.tags[data.tags.dimension + "X"];
delete data.tags[data.tags.dimension + "Y"];
delete data.tags[data.tags.dimension + "Z"];
delete data.tags[data.tags.dimension + "RotationX"];
delete data.tags[data.tags.dimension + "RotationY"];
delete data.tags[data.tags.dimension + "RotationZ"];
delete data.tags[data.tags.dimension];
delete data.tags.dimension;
delete data.tags.modelAttributes;
delete data.tags.modelAttributesStartingValues;
delete data.tags.statsButton;
delete data.tags.scaleX;
delete data.tags.scaleY;
delete data.tags.scaleZ;
delete data.tags.modelLocked;
delete data.tags.currentValues;
delete data.tags.formAddress;
delete data.tags.form;
delete data.tags.formSubtype;
delete data.tags.modelName;