const properties: ABConfiguratorProperty[] = [
    {
        key: 'greenBotLists',
        type: 'group',
        label: 'Green Bot Lists',
        description: 'Examples of dynamic list properties (simple and complex).',
        properties: [
            {
                key: 'greenBotFavoriteNumbers',
                type: 'list',
                label: 'Favorite Numbers',
                description: 'A simple list of integers between 0 and 100.',
                default: [1, 2, 3],
                value: tags.favoriteNumbers,
                itemSchema: {
                    key: 'favoriteNumber',
                    type: 'number',
                    min: 0,
                    max: 100,
                    integer: true,
                    default: 0,
                },
            },
            {
                key: 'greenBotNicknames',
                type: 'list',
                label: 'Nicknames',
                description: 'A simple list of text nicknames.',
                default: ['greenie', 'sproutling'],
                value: tags.nicknames,
                itemSchema: {
                    key: 'nickname',
                    type: 'text',
                    default: 'unnamed',
                },
            },
            {
                key: 'greenBotFlags',
                type: 'list',
                label: 'Boolean Flags',
                description: 'A simple list of boolean flags.',
                default: [true, false, true],
                value: tags.flags,
                itemSchema: {
                    key: 'flag',
                    type: 'boolean',
                    default: false,
                },
            },
            {
                key: 'greenBotWaypoints',
                type: 'list',
                label: 'Waypoints',
                description: 'Complex list — text + two numbers.',
                default: [{ name: 'origin', x: 0, y: 0 }],
                value: tags.waypoints,
                itemSchema: {
                    key: 'waypoint',
                    type: 'group',
                    properties: [
                        { key: 'name', type: 'text', default: 'unnamed', label: 'Name' },
                        { key: 'x', type: 'number', default: 0, label: 'X' },
                        { key: 'y', type: 'number', default: 0, label: 'Y' },
                    ],
                },
            },
            {
                key: 'greenBotTodos',
                type: 'list',
                label: 'Todo Items',
                description: 'Complex list — text + boolean + bounded integer priority.',
                default: [
                    { task: 'water the plants', done: false, priority: 1 },
                    { task: 'feed the cat', done: true, priority: 3 },
                ],
                value: tags.todos,
                itemSchema: {
                    key: 'todo',
                    type: 'group',
                    properties: [
                        { key: 'task', type: 'text', default: 'new task', label: 'Task' },
                        { key: 'done', type: 'boolean', default: false, label: 'Done' },
                        { key: 'priority', type: 'number', min: 1, max: 5, integer: true, default: 1, label: 'Priority (1-5)' },
                    ],
                },
            },
            {
                key: 'greenBotContacts',
                type: 'list',
                label: 'Contacts',
                description: 'Complex list — multiple text fields, a number, and a boolean.',
                default: [
                    { name: 'Alice', email: 'alice@example.com', age: 30, vip: true },
                ],
                value: tags.contacts,
                itemSchema: {
                    key: 'contact',
                    type: 'group',
                    properties: [
                        { key: 'name', type: 'text', default: 'unnamed', label: 'Name' },
                        { key: 'email', type: 'text', default: '', label: 'Email' },
                        { key: 'age', type: 'number', min: 0, max: 150, integer: true, default: 0, label: 'Age' },
                        { key: 'vip', type: 'boolean', default: false, label: 'VIP' },
                    ],
                },
            },
            {
                key: 'greenBotFavoriteColors',
                type: 'list',
                label: 'Favorite Colors',
                description: 'Simple list of color values.',
                default: ['#ff5252', '#3b82f6'],
                value: tags.favoriteColors,
                itemSchema: {
                    key: 'favoriteColor',
                    type: 'color',
                    default: '#ffffff',
                },
            },
            {
                key: 'greenBotFavoriteFruits',
                type: 'list',
                label: 'Favorite Fruits',
                description: 'Simple list — each entry is one selection from a fixed option set.',
                default: ['apple', 'banana'],
                value: tags.favoriteFruits,
                itemSchema: {
                    key: 'favoriteFruit',
                    type: 'select',
                    default: 'apple',
                    options: [
                        { value: 'apple', label: 'Apple' },
                        { value: 'banana', label: 'Banana' },
                        { value: 'cherry', label: 'Cherry' },
                        { value: 'durian', label: 'Durian' },
                        { value: 'elderberry', label: 'Elderberry' },
                    ],
                },
            },
            {
                key: 'greenBotInterestSets',
                type: 'list',
                label: 'Interest Sets',
                description: 'Simple list — each entry is itself a multiselect set of interests.',
                default: [
                    ['sports', 'music'],
                    ['movies'],
                ],
                value: tags.interestSets,
                itemSchema: {
                    key: 'interestSet',
                    type: 'multiselect',
                    default: [],
                    options: [
                        { value: 'sports', label: 'Sports' },
                        { value: 'music', label: 'Music' },
                        { value: 'movies', label: 'Movies' },
                        { value: 'videogames', label: 'Video Games' },
                        { value: 'reading', label: 'Reading' },
                    ],
                },
            },
            {
                key: 'greenBotPalettes',
                type: 'list',
                label: 'Palettes',
                description: 'Complex list mixing text, color, select, and multiselect fields.',
                default: [
                    {
                        name: 'sunset',
                        primaryColor: '#ff7e5f',
                        accent: 'warm',
                        moods: ['cozy', 'romantic'],
                    },
                ],
                value: tags.palettes,
                itemSchema: {
                    key: 'palette',
                    type: 'group',
                    properties: [
                        { key: 'name', type: 'text', default: 'unnamed', label: 'Name' },
                        { key: 'primaryColor', type: 'color', default: '#ffffff', label: 'Primary Color' },
                        {
                            key: 'accent',
                            type: 'select',
                            default: 'warm',
                            label: 'Accent',
                            options: [
                                { value: 'warm', label: 'Warm' },
                                { value: 'cool', label: 'Cool' },
                                { value: 'neutral', label: 'Neutral' },
                            ],
                        },
                        {
                            key: 'moods',
                            type: 'multiselect',
                            default: [],
                            label: 'Moods',
                            options: [
                                { value: 'cozy', label: 'Cozy' },
                                { value: 'energetic', label: 'Energetic' },
                                { value: 'romantic', label: 'Romantic' },
                                { value: 'mysterious', label: 'Mysterious' },
                            ],
                        },
                    ],
                },
            },
        ],
    },
];

return properties;
