const nums = tags.favoriteNumbers ?? [];
const nicknames = tags.nicknames ?? [];
const flags = tags.flags ?? [];
const wps = tags.waypoints ?? [];
const todos = tags.todos ?? [];
const contacts = tags.contacts ?? [];
const colors = tags.favoriteColors ?? [];
const fruits = tags.favoriteFruits ?? [];
const interestSets = tags.interestSets ?? [];
const palettes = tags.palettes ?? [];
os.toast(`green bot: ${nums.length} numbers, ${nicknames.length} nicknames, ${flags.length} flags, ${wps.length} waypoints, ${todos.length} todos, ${contacts.length} contacts, ${colors.length} colors, ${fruits.length} fruits, ${interestSets.length} interest sets, ${palettes.length} palettes`, 4);
